// This file is auto-generated by @hey-api/openapi-ts

import {
	type InfiniteData,
	infiniteQueryOptions,
	queryOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
	getIncidents,
	getIncidentsById,
	getIncidentsByIdOg,
	type Options,
} from "../sdk.gen";
import type {
	GetIncidentsByIdData,
	GetIncidentsByIdError,
	GetIncidentsByIdOgData,
	GetIncidentsByIdOgError,
	GetIncidentsByIdOgResponse,
	GetIncidentsByIdResponse,
	GetIncidentsData,
	GetIncidentsError,
	GetIncidentsResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
	Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
		_id: string;
		_infinite?: boolean;
		tags?: ReadonlyArray<string>;
	},
];

const createQueryKey = <TOptions extends Options>(
	id: string,
	options?: TOptions,
	infinite?: boolean,
	tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
	const params: QueryKey<TOptions>[0] = {
		_id: id,
		baseUrl:
			options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
	} as QueryKey<TOptions>[0];
	if (infinite) {
		params._infinite = infinite;
	}
	if (tags) {
		params.tags = tags;
	}
	if (options?.body) {
		params.body = options.body;
	}
	if (options?.headers) {
		params.headers = options.headers;
	}
	if (options?.path) {
		params.path = options.path;
	}
	if (options?.query) {
		params.query = options.query;
	}
	return [params];
};

export const getIncidentsQueryKey = (options?: Options<GetIncidentsData>) =>
	createQueryKey("getIncidents", options);

export const getIncidentsOptions = (options?: Options<GetIncidentsData>) =>
	queryOptions<
		GetIncidentsResponse,
		GetIncidentsError,
		GetIncidentsResponse,
		ReturnType<typeof getIncidentsQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await getIncidents({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			});
			return data;
		},
		queryKey: getIncidentsQueryKey(options),
	});

const createInfiniteParams = <
	K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
	queryKey: QueryKey<Options>,
	page: K,
) => {
	const params = { ...queryKey[0] };
	if (page.body) {
		params.body = {
			...(queryKey[0].body as any),
			...(page.body as any),
		};
	}
	if (page.headers) {
		params.headers = {
			...queryKey[0].headers,
			...page.headers,
		};
	}
	if (page.path) {
		params.path = {
			...(queryKey[0].path as any),
			...(page.path as any),
		};
	}
	if (page.query) {
		params.query = {
			...(queryKey[0].query as any),
			...(page.query as any),
		};
	}
	return params as unknown as typeof page;
};

export const getIncidentsInfiniteQueryKey = (
	options?: Options<GetIncidentsData>,
): QueryKey<Options<GetIncidentsData>> =>
	createQueryKey("getIncidents", options, true);

export const getIncidentsInfiniteOptions = (
	options?: Options<GetIncidentsData>,
) =>
	infiniteQueryOptions<
		GetIncidentsResponse,
		GetIncidentsError,
		InfiniteData<GetIncidentsResponse>,
		QueryKey<Options<GetIncidentsData>>,
		| number
		| null
		| Pick<
				QueryKey<Options<GetIncidentsData>>[0],
				"body" | "headers" | "path" | "query"
		  >
	>(
		// @ts-ignore
		{
			queryFn: async ({ pageParam, queryKey, signal }) => {
				// @ts-ignore
				const page: Pick<
					QueryKey<Options<GetIncidentsData>>[0],
					"body" | "headers" | "path" | "query"
				> =
					typeof pageParam === "object"
						? pageParam
						: {
								query: {
									cursor: pageParam,
								},
							};
				const params = createInfiniteParams(queryKey, page);
				const { data } = await getIncidents({
					...options,
					...params,
					signal,
					throwOnError: true,
				});
				return data;
			},
			queryKey: getIncidentsInfiniteQueryKey(options),
		},
	);

export const getIncidentsByIdQueryKey = (
	options: Options<GetIncidentsByIdData>,
) => createQueryKey("getIncidentsById", options);

export const getIncidentsByIdOptions = (
	options: Options<GetIncidentsByIdData>,
) =>
	queryOptions<
		GetIncidentsByIdResponse,
		GetIncidentsByIdError,
		GetIncidentsByIdResponse,
		ReturnType<typeof getIncidentsByIdQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await getIncidentsById({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			});
			return data;
		},
		queryKey: getIncidentsByIdQueryKey(options),
	});

export const getIncidentsByIdOgQueryKey = (
	options: Options<GetIncidentsByIdOgData>,
) => createQueryKey("getIncidentsByIdOg", options);

export const getIncidentsByIdOgOptions = (
	options: Options<GetIncidentsByIdOgData>,
) =>
	queryOptions<
		GetIncidentsByIdOgResponse,
		GetIncidentsByIdOgError,
		GetIncidentsByIdOgResponse,
		ReturnType<typeof getIncidentsByIdOgQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await getIncidentsByIdOg({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			});
			return data;
		},
		queryKey: getIncidentsByIdOgQueryKey(options),
	});
