// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getAdminIncidents, getIncidents, getIncidentsById, getIncidentsByIdMap, getIncidentsByIdMapOriginal, getIncidentsByIdOg, getIncidentsByIdResponseTimes, getIncidentsByIdTimeline, getIncidentsHighlighted, getStations, getStationsByKey, getStationsByKeyImage, getStationsByKeyImageOriginal, getStatsYearRecap, type Options, postAdminIncidents, postAdminIncidentsById } from '../sdk.gen';
import type { GetAdminIncidentsData, GetAdminIncidentsError, GetAdminIncidentsResponse, GetIncidentsByIdData, GetIncidentsByIdError, GetIncidentsByIdMapData, GetIncidentsByIdMapError, GetIncidentsByIdMapOriginalData, GetIncidentsByIdMapOriginalError, GetIncidentsByIdMapOriginalResponse, GetIncidentsByIdMapResponse, GetIncidentsByIdOgData, GetIncidentsByIdOgError, GetIncidentsByIdOgResponse, GetIncidentsByIdResponse, GetIncidentsByIdResponseTimesData, GetIncidentsByIdResponseTimesError, GetIncidentsByIdResponseTimesResponse, GetIncidentsByIdTimelineData, GetIncidentsByIdTimelineError, GetIncidentsByIdTimelineResponse, GetIncidentsData, GetIncidentsError, GetIncidentsHighlightedData, GetIncidentsHighlightedResponse, GetIncidentsResponse, GetStationsByKeyData, GetStationsByKeyError, GetStationsByKeyImageData, GetStationsByKeyImageError, GetStationsByKeyImageOriginalData, GetStationsByKeyImageOriginalError, GetStationsByKeyImageOriginalResponse, GetStationsByKeyImageResponse, GetStationsByKeyResponse, GetStationsData, GetStationsResponse, GetStatsYearRecapData, GetStatsYearRecapResponse, PostAdminIncidentsByIdData, PostAdminIncidentsByIdError, PostAdminIncidentsByIdResponse, PostAdminIncidentsData, PostAdminIncidentsError, PostAdminIncidentsResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getIncidentsQueryKey = (options?: Options<GetIncidentsData>) => createQueryKey('getIncidents', options);

export const getIncidentsOptions = (options?: Options<GetIncidentsData>) => queryOptions<GetIncidentsResponse, GetIncidentsError, GetIncidentsResponse, ReturnType<typeof getIncidentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIncidents({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIncidentsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getIncidentsInfiniteQueryKey = (options?: Options<GetIncidentsData>): QueryKey<Options<GetIncidentsData>> => createQueryKey('getIncidents', options, true);

export const getIncidentsInfiniteOptions = (options?: Options<GetIncidentsData>) => infiniteQueryOptions<GetIncidentsResponse, GetIncidentsError, InfiniteData<GetIncidentsResponse>, QueryKey<Options<GetIncidentsData>>, number | null | Pick<QueryKey<Options<GetIncidentsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetIncidentsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                cursor: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getIncidents({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIncidentsInfiniteQueryKey(options)
});

export const getIncidentsHighlightedQueryKey = (options?: Options<GetIncidentsHighlightedData>) => createQueryKey('getIncidentsHighlighted', options);

export const getIncidentsHighlightedOptions = (options?: Options<GetIncidentsHighlightedData>) => queryOptions<GetIncidentsHighlightedResponse, DefaultError, GetIncidentsHighlightedResponse, ReturnType<typeof getIncidentsHighlightedQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIncidentsHighlighted({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIncidentsHighlightedQueryKey(options)
});

export const getIncidentsByIdQueryKey = (options: Options<GetIncidentsByIdData>) => createQueryKey('getIncidentsById', options);

export const getIncidentsByIdOptions = (options: Options<GetIncidentsByIdData>) => queryOptions<GetIncidentsByIdResponse, GetIncidentsByIdError, GetIncidentsByIdResponse, ReturnType<typeof getIncidentsByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIncidentsById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIncidentsByIdQueryKey(options)
});

export const getIncidentsByIdTimelineQueryKey = (options: Options<GetIncidentsByIdTimelineData>) => createQueryKey('getIncidentsByIdTimeline', options);

export const getIncidentsByIdTimelineOptions = (options: Options<GetIncidentsByIdTimelineData>) => queryOptions<GetIncidentsByIdTimelineResponse, GetIncidentsByIdTimelineError, GetIncidentsByIdTimelineResponse, ReturnType<typeof getIncidentsByIdTimelineQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIncidentsByIdTimeline({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIncidentsByIdTimelineQueryKey(options)
});

export const getIncidentsByIdResponseTimesQueryKey = (options: Options<GetIncidentsByIdResponseTimesData>) => createQueryKey('getIncidentsByIdResponseTimes', options);

export const getIncidentsByIdResponseTimesOptions = (options: Options<GetIncidentsByIdResponseTimesData>) => queryOptions<GetIncidentsByIdResponseTimesResponse, GetIncidentsByIdResponseTimesError, GetIncidentsByIdResponseTimesResponse, ReturnType<typeof getIncidentsByIdResponseTimesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIncidentsByIdResponseTimes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIncidentsByIdResponseTimesQueryKey(options)
});

export const getIncidentsByIdOgQueryKey = (options: Options<GetIncidentsByIdOgData>) => createQueryKey('getIncidentsByIdOg', options);

export const getIncidentsByIdOgOptions = (options: Options<GetIncidentsByIdOgData>) => queryOptions<GetIncidentsByIdOgResponse, GetIncidentsByIdOgError, GetIncidentsByIdOgResponse, ReturnType<typeof getIncidentsByIdOgQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIncidentsByIdOg({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIncidentsByIdOgQueryKey(options)
});

export const getIncidentsByIdMapOriginalQueryKey = (options: Options<GetIncidentsByIdMapOriginalData>) => createQueryKey('getIncidentsByIdMapOriginal', options);

export const getIncidentsByIdMapOriginalOptions = (options: Options<GetIncidentsByIdMapOriginalData>) => queryOptions<GetIncidentsByIdMapOriginalResponse, GetIncidentsByIdMapOriginalError, GetIncidentsByIdMapOriginalResponse, ReturnType<typeof getIncidentsByIdMapOriginalQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIncidentsByIdMapOriginal({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIncidentsByIdMapOriginalQueryKey(options)
});

export const getIncidentsByIdMapQueryKey = (options: Options<GetIncidentsByIdMapData>) => createQueryKey('getIncidentsByIdMap', options);

export const getIncidentsByIdMapOptions = (options: Options<GetIncidentsByIdMapData>) => queryOptions<GetIncidentsByIdMapResponse, GetIncidentsByIdMapError, GetIncidentsByIdMapResponse, ReturnType<typeof getIncidentsByIdMapQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIncidentsByIdMap({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIncidentsByIdMapQueryKey(options)
});

export const getStationsQueryKey = (options?: Options<GetStationsData>) => createQueryKey('getStations', options);

export const getStationsOptions = (options?: Options<GetStationsData>) => queryOptions<GetStationsResponse, DefaultError, GetStationsResponse, ReturnType<typeof getStationsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStations({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStationsQueryKey(options)
});

export const getStationsInfiniteQueryKey = (options?: Options<GetStationsData>): QueryKey<Options<GetStationsData>> => createQueryKey('getStations', options, true);

export const getStationsInfiniteOptions = (options?: Options<GetStationsData>) => infiniteQueryOptions<GetStationsResponse, DefaultError, InfiniteData<GetStationsResponse>, QueryKey<Options<GetStationsData>>, number | null | Pick<QueryKey<Options<GetStationsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetStationsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                cursor: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getStations({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStationsInfiniteQueryKey(options)
});

export const getStationsByKeyQueryKey = (options: Options<GetStationsByKeyData>) => createQueryKey('getStationsByKey', options);

export const getStationsByKeyOptions = (options: Options<GetStationsByKeyData>) => queryOptions<GetStationsByKeyResponse, GetStationsByKeyError, GetStationsByKeyResponse, ReturnType<typeof getStationsByKeyQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStationsByKey({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStationsByKeyQueryKey(options)
});

export const getStationsByKeyImageOriginalQueryKey = (options: Options<GetStationsByKeyImageOriginalData>) => createQueryKey('getStationsByKeyImageOriginal', options);

export const getStationsByKeyImageOriginalOptions = (options: Options<GetStationsByKeyImageOriginalData>) => queryOptions<GetStationsByKeyImageOriginalResponse, GetStationsByKeyImageOriginalError, GetStationsByKeyImageOriginalResponse, ReturnType<typeof getStationsByKeyImageOriginalQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStationsByKeyImageOriginal({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStationsByKeyImageOriginalQueryKey(options)
});

export const getStationsByKeyImageQueryKey = (options: Options<GetStationsByKeyImageData>) => createQueryKey('getStationsByKeyImage', options);

export const getStationsByKeyImageOptions = (options: Options<GetStationsByKeyImageData>) => queryOptions<GetStationsByKeyImageResponse, GetStationsByKeyImageError, GetStationsByKeyImageResponse, ReturnType<typeof getStationsByKeyImageQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStationsByKeyImage({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStationsByKeyImageQueryKey(options)
});

export const getAdminIncidentsQueryKey = (options: Options<GetAdminIncidentsData>) => createQueryKey('getAdminIncidents', options);

export const getAdminIncidentsOptions = (options: Options<GetAdminIncidentsData>) => queryOptions<GetAdminIncidentsResponse, GetAdminIncidentsError, GetAdminIncidentsResponse, ReturnType<typeof getAdminIncidentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAdminIncidents({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAdminIncidentsQueryKey(options)
});

export const postAdminIncidentsMutation = (options?: Partial<Options<PostAdminIncidentsData>>): UseMutationOptions<PostAdminIncidentsResponse, PostAdminIncidentsError, Options<PostAdminIncidentsData>> => {
    const mutationOptions: UseMutationOptions<PostAdminIncidentsResponse, PostAdminIncidentsError, Options<PostAdminIncidentsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAdminIncidents({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postAdminIncidentsByIdMutation = (options?: Partial<Options<PostAdminIncidentsByIdData>>): UseMutationOptions<PostAdminIncidentsByIdResponse, PostAdminIncidentsByIdError, Options<PostAdminIncidentsByIdData>> => {
    const mutationOptions: UseMutationOptions<PostAdminIncidentsByIdResponse, PostAdminIncidentsByIdError, Options<PostAdminIncidentsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAdminIncidentsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getStatsYearRecapQueryKey = (options?: Options<GetStatsYearRecapData>) => createQueryKey('getStatsYearRecap', options);

export const getStatsYearRecapOptions = (options?: Options<GetStatsYearRecapData>) => queryOptions<GetStatsYearRecapResponse, DefaultError, GetStatsYearRecapResponse, ReturnType<typeof getStatsYearRecapQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStatsYearRecap({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStatsYearRecapQueryKey(options)
});
