/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IncidentesIndexRouteImport } from './routes/incidentes/index'
import { Route as EstacionesIndexRouteImport } from './routes/estaciones/index'
import { Route as IncidentesSlugRouteImport } from './routes/incidentes/$slug'
import { Route as EstacionesNameRouteImport } from './routes/estaciones/$name'

const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentesIndexRoute = IncidentesIndexRouteImport.update({
  id: '/incidentes/',
  path: '/incidentes/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstacionesIndexRoute = EstacionesIndexRouteImport.update({
  id: '/estaciones/',
  path: '/estaciones/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentesSlugRoute = IncidentesSlugRouteImport.update({
  id: '/incidentes/$slug',
  path: '/incidentes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EstacionesNameRoute = EstacionesNameRouteImport.update({
  id: '/estaciones/$name',
  path: '/estaciones/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/estaciones/$name': typeof EstacionesNameRoute
  '/incidentes/$slug': typeof IncidentesSlugRoute
  '/estaciones': typeof EstacionesIndexRoute
  '/incidentes': typeof IncidentesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/estaciones/$name': typeof EstacionesNameRoute
  '/incidentes/$slug': typeof IncidentesSlugRoute
  '/estaciones': typeof EstacionesIndexRoute
  '/incidentes': typeof IncidentesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/estaciones/$name': typeof EstacionesNameRoute
  '/incidentes/$slug': typeof IncidentesSlugRoute
  '/estaciones/': typeof EstacionesIndexRoute
  '/incidentes/': typeof IncidentesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mapa'
    | '/estaciones/$name'
    | '/incidentes/$slug'
    | '/estaciones'
    | '/incidentes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mapa'
    | '/estaciones/$name'
    | '/incidentes/$slug'
    | '/estaciones'
    | '/incidentes'
  id:
    | '__root__'
    | '/'
    | '/mapa'
    | '/estaciones/$name'
    | '/incidentes/$slug'
    | '/estaciones/'
    | '/incidentes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapaRoute: typeof MapaRoute
  EstacionesNameRoute: typeof EstacionesNameRoute
  IncidentesSlugRoute: typeof IncidentesSlugRoute
  EstacionesIndexRoute: typeof EstacionesIndexRoute
  IncidentesIndexRoute: typeof IncidentesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidentes/': {
      id: '/incidentes/'
      path: '/incidentes'
      fullPath: '/incidentes'
      preLoaderRoute: typeof IncidentesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estaciones/': {
      id: '/estaciones/'
      path: '/estaciones'
      fullPath: '/estaciones'
      preLoaderRoute: typeof EstacionesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidentes/$slug': {
      id: '/incidentes/$slug'
      path: '/incidentes/$slug'
      fullPath: '/incidentes/$slug'
      preLoaderRoute: typeof IncidentesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estaciones/$name': {
      id: '/estaciones/$name'
      path: '/estaciones/$name'
      fullPath: '/estaciones/$name'
      preLoaderRoute: typeof EstacionesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapaRoute: MapaRoute,
  EstacionesNameRoute: EstacionesNameRoute,
  IncidentesSlugRoute: IncidentesSlugRoute,
  EstacionesIndexRoute: EstacionesIndexRoute,
  IncidentesIndexRoute: IncidentesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
