/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IncidentsRouteImport } from './routes/_incidents'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as IncidentsIncidentesIndexRouteImport } from './routes/_incidents/incidentes/index'
import { Route as DashboardEstacionesIndexRouteImport } from './routes/_dashboard/estaciones/index'
import { Route as DashboardIncidentesSlugRouteImport } from './routes/_dashboard/incidentes/$slug'
import { Route as DashboardEstacionesNameRouteImport } from './routes/_dashboard/estaciones/$name'

const IncidentsRoute = IncidentsRouteImport.update({
  id: '/_incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const IncidentsIncidentesIndexRoute =
  IncidentsIncidentesIndexRouteImport.update({
    id: '/incidentes/',
    path: '/incidentes/',
    getParentRoute: () => IncidentsRoute,
  } as any)
const DashboardEstacionesIndexRoute =
  DashboardEstacionesIndexRouteImport.update({
    id: '/estaciones/',
    path: '/estaciones/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardIncidentesSlugRoute = DashboardIncidentesSlugRouteImport.update({
  id: '/incidentes/$slug',
  path: '/incidentes/$slug',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEstacionesNameRoute = DashboardEstacionesNameRouteImport.update({
  id: '/estaciones/$name',
  path: '/estaciones/$name',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/estaciones/$name': typeof DashboardEstacionesNameRoute
  '/incidentes/$slug': typeof DashboardIncidentesSlugRoute
  '/estaciones': typeof DashboardEstacionesIndexRoute
  '/incidentes': typeof IncidentsIncidentesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/estaciones/$name': typeof DashboardEstacionesNameRoute
  '/incidentes/$slug': typeof DashboardIncidentesSlugRoute
  '/estaciones': typeof DashboardEstacionesIndexRoute
  '/incidentes': typeof IncidentsIncidentesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_incidents': typeof IncidentsRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/estaciones/$name': typeof DashboardEstacionesNameRoute
  '/_dashboard/incidentes/$slug': typeof DashboardIncidentesSlugRoute
  '/_dashboard/estaciones/': typeof DashboardEstacionesIndexRoute
  '/_incidents/incidentes/': typeof IncidentsIncidentesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/estaciones/$name'
    | '/incidentes/$slug'
    | '/estaciones'
    | '/incidentes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/estaciones/$name'
    | '/incidentes/$slug'
    | '/estaciones'
    | '/incidentes'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_incidents'
    | '/_dashboard/'
    | '/_dashboard/estaciones/$name'
    | '/_dashboard/incidentes/$slug'
    | '/_dashboard/estaciones/'
    | '/_incidents/incidentes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  IncidentsRoute: typeof IncidentsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_incidents': {
      id: '/_incidents'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_incidents/incidentes/': {
      id: '/_incidents/incidentes/'
      path: '/incidentes'
      fullPath: '/incidentes'
      preLoaderRoute: typeof IncidentsIncidentesIndexRouteImport
      parentRoute: typeof IncidentsRoute
    }
    '/_dashboard/estaciones/': {
      id: '/_dashboard/estaciones/'
      path: '/estaciones'
      fullPath: '/estaciones'
      preLoaderRoute: typeof DashboardEstacionesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/incidentes/$slug': {
      id: '/_dashboard/incidentes/$slug'
      path: '/incidentes/$slug'
      fullPath: '/incidentes/$slug'
      preLoaderRoute: typeof DashboardIncidentesSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/estaciones/$name': {
      id: '/_dashboard/estaciones/$name'
      path: '/estaciones/$name'
      fullPath: '/estaciones/$name'
      preLoaderRoute: typeof DashboardEstacionesNameRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEstacionesNameRoute: typeof DashboardEstacionesNameRoute
  DashboardIncidentesSlugRoute: typeof DashboardIncidentesSlugRoute
  DashboardEstacionesIndexRoute: typeof DashboardEstacionesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEstacionesNameRoute: DashboardEstacionesNameRoute,
  DashboardIncidentesSlugRoute: DashboardIncidentesSlugRoute,
  DashboardEstacionesIndexRoute: DashboardEstacionesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface IncidentsRouteChildren {
  IncidentsIncidentesIndexRoute: typeof IncidentsIncidentesIndexRoute
}

const IncidentsRouteChildren: IncidentsRouteChildren = {
  IncidentsIncidentesIndexRoute: IncidentsIncidentesIndexRoute,
}

const IncidentsRouteWithChildren = IncidentsRoute._addFileChildren(
  IncidentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  IncidentsRoute: IncidentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
