// This file is auto-generated by @hey-api/openapi-ts

export { getIncidents, getIncidentsById, getIncidentsByIdOg, type Options } from "./sdk.gen";
export type {
  ClientOptions,
  GetIncidentsByIdData,
  GetIncidentsByIdError,
  GetIncidentsByIdErrors,
  GetIncidentsByIdOgData,
  GetIncidentsByIdOgError,
  GetIncidentsByIdOgErrors,
  GetIncidentsByIdOgResponse,
  GetIncidentsByIdOgResponses,
  GetIncidentsByIdResponse,
  GetIncidentsByIdResponses,
  GetIncidentsData,
  GetIncidentsError,
  GetIncidentsErrors,
  GetIncidentsResponse,
  GetIncidentsResponses
} from "./types.gen";
