// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetAdminIncidentsData, GetAdminIncidentsErrors, GetAdminIncidentsResponses, GetIncidentsByIdData, GetIncidentsByIdErrors, GetIncidentsByIdMapData, GetIncidentsByIdMapErrors, GetIncidentsByIdMapOriginalData, GetIncidentsByIdMapOriginalErrors, GetIncidentsByIdMapOriginalResponses, GetIncidentsByIdMapResponses, GetIncidentsByIdOgData, GetIncidentsByIdOgErrors, GetIncidentsByIdOgResponses, GetIncidentsByIdResponses, GetIncidentsByIdResponseTimesData, GetIncidentsByIdResponseTimesErrors, GetIncidentsByIdResponseTimesResponses, GetIncidentsByIdTimelineData, GetIncidentsByIdTimelineErrors, GetIncidentsByIdTimelineResponses, GetIncidentsData, GetIncidentsErrors, GetIncidentsHighlightedData, GetIncidentsHighlightedResponses, GetIncidentsResponses, GetStationsByKeyData, GetStationsByKeyErrors, GetStationsByKeyImageData, GetStationsByKeyImageErrors, GetStationsByKeyImageOriginalData, GetStationsByKeyImageOriginalErrors, GetStationsByKeyImageOriginalResponses, GetStationsByKeyImageResponses, GetStationsByKeyResponses, GetStationsData, GetStationsResponses, PostAdminIncidentsByIdData, PostAdminIncidentsByIdErrors, PostAdminIncidentsByIdResponses, PostAdminIncidentsData, PostAdminIncidentsErrors, PostAdminIncidentsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getIncidents = <ThrowOnError extends boolean = false>(options?: Options<GetIncidentsData, ThrowOnError>) => (options?.client ?? client).get<GetIncidentsResponses, GetIncidentsErrors, ThrowOnError>({ url: '/incidents', ...options });

export const getIncidentsHighlighted = <ThrowOnError extends boolean = false>(options?: Options<GetIncidentsHighlightedData, ThrowOnError>) => (options?.client ?? client).get<GetIncidentsHighlightedResponses, unknown, ThrowOnError>({ url: '/incidents/highlighted', ...options });

export const getIncidentsById = <ThrowOnError extends boolean = false>(options: Options<GetIncidentsByIdData, ThrowOnError>) => (options.client ?? client).get<GetIncidentsByIdResponses, GetIncidentsByIdErrors, ThrowOnError>({ url: '/incidents/{id}', ...options });

export const getIncidentsByIdTimeline = <ThrowOnError extends boolean = false>(options: Options<GetIncidentsByIdTimelineData, ThrowOnError>) => (options.client ?? client).get<GetIncidentsByIdTimelineResponses, GetIncidentsByIdTimelineErrors, ThrowOnError>({ url: '/incidents/{id}/timeline', ...options });

export const getIncidentsByIdResponseTimes = <ThrowOnError extends boolean = false>(options: Options<GetIncidentsByIdResponseTimesData, ThrowOnError>) => (options.client ?? client).get<GetIncidentsByIdResponseTimesResponses, GetIncidentsByIdResponseTimesErrors, ThrowOnError>({ url: '/incidents/{id}/response-times', ...options });

export const getIncidentsByIdOg = <ThrowOnError extends boolean = false>(options: Options<GetIncidentsByIdOgData, ThrowOnError>) => (options.client ?? client).get<GetIncidentsByIdOgResponses, GetIncidentsByIdOgErrors, ThrowOnError>({ url: '/incidents/{id}/og', ...options });

export const getIncidentsByIdMapOriginal = <ThrowOnError extends boolean = false>(options: Options<GetIncidentsByIdMapOriginalData, ThrowOnError>) => (options.client ?? client).get<GetIncidentsByIdMapOriginalResponses, GetIncidentsByIdMapOriginalErrors, ThrowOnError>({ url: '/incidents/{id}/map/original', ...options });

export const getIncidentsByIdMap = <ThrowOnError extends boolean = false>(options: Options<GetIncidentsByIdMapData, ThrowOnError>) => (options.client ?? client).get<GetIncidentsByIdMapResponses, GetIncidentsByIdMapErrors, ThrowOnError>({ url: '/incidents/{id}/map', ...options });

export const getStations = <ThrowOnError extends boolean = false>(options?: Options<GetStationsData, ThrowOnError>) => (options?.client ?? client).get<GetStationsResponses, unknown, ThrowOnError>({ url: '/stations', ...options });

export const getStationsByKey = <ThrowOnError extends boolean = false>(options: Options<GetStationsByKeyData, ThrowOnError>) => (options.client ?? client).get<GetStationsByKeyResponses, GetStationsByKeyErrors, ThrowOnError>({ url: '/stations/{key}', ...options });

export const getStationsByKeyImageOriginal = <ThrowOnError extends boolean = false>(options: Options<GetStationsByKeyImageOriginalData, ThrowOnError>) => (options.client ?? client).get<GetStationsByKeyImageOriginalResponses, GetStationsByKeyImageOriginalErrors, ThrowOnError>({ url: '/stations/{key}/image/original', ...options });

export const getStationsByKeyImage = <ThrowOnError extends boolean = false>(options: Options<GetStationsByKeyImageData, ThrowOnError>) => (options.client ?? client).get<GetStationsByKeyImageResponses, GetStationsByKeyImageErrors, ThrowOnError>({ url: '/stations/{key}/image', ...options });

export const getAdminIncidents = <ThrowOnError extends boolean = false>(options: Options<GetAdminIncidentsData, ThrowOnError>) => (options.client ?? client).get<GetAdminIncidentsResponses, GetAdminIncidentsErrors, ThrowOnError>({ url: '/admin/incidents', ...options });

export const postAdminIncidents = <ThrowOnError extends boolean = false>(options?: Options<PostAdminIncidentsData, ThrowOnError>) => (options?.client ?? client).post<PostAdminIncidentsResponses, PostAdminIncidentsErrors, ThrowOnError>({
    url: '/admin/incidents',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const postAdminIncidentsById = <ThrowOnError extends boolean = false>(options: Options<PostAdminIncidentsByIdData, ThrowOnError>) => (options.client ?? client).post<PostAdminIncidentsByIdResponses, PostAdminIncidentsByIdErrors, ThrowOnError>({ url: '/admin/incidents/{id}', ...options });
