// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/bomberos/hono` | (string & {});
};

export type GetIncidentsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        cursor?: number | null;
        station?: string | null;
        view?: 'default' | 'map';
        sortBy?: 'id' | 'incidentTimestamp';
        sortOrder?: 'asc' | 'desc';
        startTime?: string | null;
        endTime?: string | null;
    };
    url: '/incidents';
};

export type GetIncidentsErrors = {
    /**
     * Invalid time range (must be positive and not exceed 3 days for map view)
     */
    400: {
        message: string;
    };
};

export type GetIncidentsError = GetIncidentsErrors[keyof GetIncidentsErrors];

export type GetIncidentsResponses = {
    /**
     * List of incidents. 'default' view returns paginated results with nextCursor; 'map' view returns all matching coordinates (max 3 day range).
     */
    200: {
        view: 'default';
        incidents: Array<{
            id: number;
            slug: string;
            isOpen: boolean;
            EEConsecutive: string | null;
            address: string | null;
            incidentTimestamp: string;
            importantDetails: string | null;
            specificIncidentCode: string | null;
            incidentType: string | null;
            responsibleStation: string | null;
            specificIncidentType: string | null;
            dispatchedVehiclesCount: number;
            dispatchedStationsCount: number;
        }>;
        nextCursor: number | null;
    } | {
        view: 'map';
        incidents: Array<{
            id: number;
            slug: string;
            latitude: string;
            longitude: string;
        }>;
    };
};

export type GetIncidentsResponse = GetIncidentsResponses[keyof GetIncidentsResponses];

export type GetIncidentsHighlightedData = {
    body?: never;
    path?: never;
    query?: {
        timeRange?: number;
    };
    url: '/incidents/highlighted';
};

export type GetIncidentsHighlightedResponses = {
    /**
     * List of highlighted incidents sorted by total emergency response deployment
     */
    200: {
        incidents: Array<{
            id: number;
            slug: string;
            incidentTimestamp: string;
            details: string;
            address: string;
            responsibleStation: string;
            dispatchedVehiclesCount: number;
            dispatchedStationsCount: number;
            hasMapImage: boolean;
        }>;
    };
};

export type GetIncidentsHighlightedResponse = GetIncidentsHighlightedResponses[keyof GetIncidentsHighlightedResponses];

export type GetIncidentsByIdData = {
    body?: never;
    path: {
        id: number | null;
    };
    query?: never;
    url: '/incidents/{id}';
};

export type GetIncidentsByIdErrors = {
    /**
     * Incident not found
     */
    404: {
        message: string;
    };
};

export type GetIncidentsByIdError = GetIncidentsByIdErrors[keyof GetIncidentsByIdErrors];

export type GetIncidentsByIdResponses = {
    /**
     * Detailed incident information
     */
    200: {
        incident: {
            id: number;
            title: string;
            incidentTimestamp: string;
            dispatchType: string;
            actualType: string | null;
            address: string | null;
            isOpen: boolean;
            modifiedAt: string | null;
            cantonName: string | null;
            provinceName: string | null;
            districtName: string | null;
            location: string | null;
            latitude: string | null;
            longitude: string | null;
            hasMapImage: boolean;
            EEConsecutive: string | null;
            dispatchedVehiclesCount: number;
            dispatchedStationsCount: number;
            dispatchedStations: Array<{
                name: string;
                stationKey: string;
                isResponsible: boolean;
                vehicles: Array<{
                    internalNumber: string;
                    dispatchTime: string | null;
                    arrivalTime: string | null;
                    departureTime: string | null;
                }>;
            }>;
        };
        statistics: {
            currentYear: number;
            currentYearCount: number;
            currentYearCantonCount: number;
            previousYear: number;
            previousYearCount: number;
        };
    };
};

export type GetIncidentsByIdResponse = GetIncidentsByIdResponses[keyof GetIncidentsByIdResponses];

export type GetIncidentsByIdTimelineData = {
    body?: never;
    path: {
        id: number | null;
    };
    query?: never;
    url: '/incidents/{id}/timeline';
};

export type GetIncidentsByIdTimelineErrors = {
    /**
     * Incident not found
     */
    404: {
        message: string;
    };
};

export type GetIncidentsByIdTimelineError = GetIncidentsByIdTimelineErrors[keyof GetIncidentsByIdTimelineErrors];

export type GetIncidentsByIdTimelineResponses = {
    /**
     * Timeline events for the incident
     */
    200: {
        incidentId: number;
        events: Array<{
            id: string;
            date: string;
            title: string;
            description?: string;
        }>;
    };
};

export type GetIncidentsByIdTimelineResponse = GetIncidentsByIdTimelineResponses[keyof GetIncidentsByIdTimelineResponses];

export type GetIncidentsByIdResponseTimesData = {
    body?: never;
    path: {
        id: number | null;
    };
    query?: never;
    url: '/incidents/{id}/response-times';
};

export type GetIncidentsByIdResponseTimesErrors = {
    /**
     * Incident not found
     */
    404: {
        message: string;
    };
};

export type GetIncidentsByIdResponseTimesError = GetIncidentsByIdResponseTimesErrors[keyof GetIncidentsByIdResponseTimesErrors];

export type GetIncidentsByIdResponseTimesResponses = {
    /**
     * Response time breakdown for dispatched vehicles
     */
    200: {
        incidentId: number;
        isOpen: boolean;
        vehicles: Array<{
            id: number;
            vehicle: string;
            station: string;
            dispatchedTime: string | null;
            arrivalTime: string | null;
            departureTime: string | null;
            baseReturnTime: string | null;
            responseTimeSeconds: number;
            onSceneTimeSeconds: number;
            returnTimeSeconds: number;
            totalTimeSeconds: number;
            isEnRoute: boolean;
        }>;
    };
};

export type GetIncidentsByIdResponseTimesResponse = GetIncidentsByIdResponseTimesResponses[keyof GetIncidentsByIdResponseTimesResponses];

export type GetIncidentsByIdOgData = {
    body?: never;
    path: {
        id: number | null;
    };
    query?: never;
    url: '/incidents/{id}/og';
};

export type GetIncidentsByIdOgErrors = {
    /**
     * Incident not found
     */
    404: {
        message: string;
    };
};

export type GetIncidentsByIdOgError = GetIncidentsByIdOgErrors[keyof GetIncidentsByIdOgErrors];

export type GetIncidentsByIdOgResponses = {
    /**
     * OG Image for the incident
     */
    200: Blob | File;
};

export type GetIncidentsByIdOgResponse = GetIncidentsByIdOgResponses[keyof GetIncidentsByIdOgResponses];

export type GetIncidentsByIdMapOriginalData = {
    body?: never;
    path: {
        id: number | null;
    };
    query: {
        token: string;
    };
    url: '/incidents/{id}/map/original';
};

export type GetIncidentsByIdMapOriginalErrors = {
    /**
     * Invalid coordinates
     */
    400: {
        message: string;
    };
    /**
     * Invalid or missing token
     */
    401: {
        message: string;
    };
    /**
     * Incident not found
     */
    404: {
        message: string;
    };
    /**
     * Failed to fetch map image
     */
    502: {
        message: string;
    };
};

export type GetIncidentsByIdMapOriginalError = GetIncidentsByIdMapOriginalErrors[keyof GetIncidentsByIdMapOriginalErrors];

export type GetIncidentsByIdMapOriginalResponses = {
    /**
     * Original map image from Mapbox (PNG)
     */
    200: Blob | File;
};

export type GetIncidentsByIdMapOriginalResponse = GetIncidentsByIdMapOriginalResponses[keyof GetIncidentsByIdMapOriginalResponses];

export type GetIncidentsByIdMapData = {
    body?: never;
    path: {
        id: number | null;
    };
    query?: never;
    url: '/incidents/{id}/map';
};

export type GetIncidentsByIdMapErrors = {
    /**
     * Invalid coordinates
     */
    400: {
        message: string;
    };
    /**
     * Incident not found
     */
    404: {
        message: string;
    };
    /**
     * Failed to fetch map image
     */
    502: {
        message: string;
    };
};

export type GetIncidentsByIdMapError = GetIncidentsByIdMapErrors[keyof GetIncidentsByIdMapErrors];

export type GetIncidentsByIdMapResponses = {
    /**
     * Map image for the incident
     */
    200: Blob | File;
};

export type GetIncidentsByIdMapResponse = GetIncidentsByIdMapResponses[keyof GetIncidentsByIdMapResponses];

export type GetStationsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        page?: number;
        search?: string;
        isOperative?: boolean | null;
        view?: 'default' | 'map' | 'directory';
    };
    url: '/stations';
};

export type GetStationsResponses = {
    /**
     * Paginated list of stations
     */
    200: {
        view: 'default';
        stations: Array<{
            id: number;
            name: string;
            stationKey: string;
            address: string | null;
            latitude: string;
            longitude: string;
            isOperative: boolean | null;
        }>;
        pagination: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
            hasNext: boolean;
            hasPrev: boolean;
        };
    } | {
        view: 'map';
        stations: Array<{
            id: number;
            name: string;
            stationKey: string;
            latitude: string;
            longitude: string;
        }>;
    } | {
        view: 'directory';
        stations: Array<{
            stationKey: string;
            name: string;
            address: string | null;
        }>;
    };
};

export type GetStationsResponse = GetStationsResponses[keyof GetStationsResponses];

export type GetStationsByKeyData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/stations/{key}';
};

export type GetStationsByKeyErrors = {
    /**
     * Station not found
     */
    404: {
        message: string;
    };
};

export type GetStationsByKeyError = GetStationsByKeyErrors[keyof GetStationsByKeyErrors];

export type GetStationsByKeyResponses = {
    /**
     * Station details
     */
    200: {
        station: {
            id: number;
            name: string;
            stationKey: string;
            radioChannel: string | null;
            latitude: string;
            longitude: string;
            address: string | null;
            phoneNumber: string | null;
            fax: string | null;
            email: string | null;
            isOperative: boolean | null;
        };
    };
};

export type GetStationsByKeyResponse = GetStationsByKeyResponses[keyof GetStationsByKeyResponses];

export type GetStationsByKeyHighlightedIncidentsData = {
    body?: never;
    path: {
        key: string;
    };
    query?: {
        /**
         * Time range in days to look for incidents
         */
        timeRange?: number;
        /**
         * Maximum number of incidents to return
         */
        limit?: number;
    };
    url: '/stations/{key}/highlighted-incidents';
};

export type GetStationsByKeyHighlightedIncidentsErrors = {
    /**
     * Station not found
     */
    404: {
        message: string;
    };
};

export type GetStationsByKeyHighlightedIncidentsError = GetStationsByKeyHighlightedIncidentsErrors[keyof GetStationsByKeyHighlightedIncidentsErrors];

export type GetStationsByKeyHighlightedIncidentsResponses = {
    /**
     * Highlighted incidents for the station
     */
    200: {
        incidents: Array<{
            id: number;
            incidentTimestamp: string;
            details: string | null;
            address: string | null;
            responsibleStation: string | null;
            latitude: string;
            longitude: string;
            dispatchedVehiclesCount: number;
            dispatchedStationsCount: number;
        }>;
    };
};

export type GetStationsByKeyHighlightedIncidentsResponse = GetStationsByKeyHighlightedIncidentsResponses[keyof GetStationsByKeyHighlightedIncidentsResponses];

export type GetStationsByKeyHeatmapData = {
    body?: never;
    path: {
        key: string;
    };
    query?: {
        /**
         * Number of days to include in heatmap data
         */
        days?: number;
    };
    url: '/stations/{key}/heatmap';
};

export type GetStationsByKeyHeatmapErrors = {
    /**
     * Station not found
     */
    404: {
        message: string;
    };
};

export type GetStationsByKeyHeatmapError = GetStationsByKeyHeatmapErrors[keyof GetStationsByKeyHeatmapErrors];

export type GetStationsByKeyHeatmapResponses = {
    /**
     * Heatmap data showing incidents per day
     */
    200: {
        data: Array<{
            date: string;
            count: number;
        }>;
        totalIncidents: number;
    };
};

export type GetStationsByKeyHeatmapResponse = GetStationsByKeyHeatmapResponses[keyof GetStationsByKeyHeatmapResponses];

export type GetStationsByKeyRecentIncidentsData = {
    body?: never;
    path: {
        key: string;
    };
    query?: {
        /**
         * Maximum number of incidents to return
         */
        limit?: number;
    };
    url: '/stations/{key}/recent-incidents';
};

export type GetStationsByKeyRecentIncidentsErrors = {
    /**
     * Station not found
     */
    404: {
        message: string;
    };
};

export type GetStationsByKeyRecentIncidentsError = GetStationsByKeyRecentIncidentsErrors[keyof GetStationsByKeyRecentIncidentsErrors];

export type GetStationsByKeyRecentIncidentsResponses = {
    /**
     * Most recent incidents for the station
     */
    200: {
        incidents: Array<{
            id: number;
            incidentTimestamp: string;
            address: string | null;
            importantDetails: string | null;
            responsibleStation: string | null;
            latitude: string;
            longitude: string;
            dispatchedVehiclesCount: number;
            dispatchedStationsCount: number;
        }>;
    };
};

export type GetStationsByKeyRecentIncidentsResponse = GetStationsByKeyRecentIncidentsResponses[keyof GetStationsByKeyRecentIncidentsResponses];

export type GetStationsByKeyCollaborationsData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/stations/{key}/collaborations';
};

export type GetStationsByKeyCollaborationsErrors = {
    /**
     * Station not found
     */
    404: {
        message: string;
    };
};

export type GetStationsByKeyCollaborationsError = GetStationsByKeyCollaborationsErrors[keyof GetStationsByKeyCollaborationsErrors];

export type GetStationsByKeyCollaborationsResponses = {
    /**
     * Stations that collaborated with this one
     */
    200: {
        collaborations: Array<{
            id: number;
            name: string;
            stationKey: string;
            collaborationCount: number;
        }>;
    };
};

export type GetStationsByKeyCollaborationsResponse = GetStationsByKeyCollaborationsResponses[keyof GetStationsByKeyCollaborationsResponses];

export type GetStationsByKeyVehiclesData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/stations/{key}/vehicles';
};

export type GetStationsByKeyVehiclesErrors = {
    /**
     * Station not found
     */
    404: {
        message: string;
    };
};

export type GetStationsByKeyVehiclesError = GetStationsByKeyVehiclesErrors[keyof GetStationsByKeyVehiclesErrors];

export type GetStationsByKeyVehiclesResponses = {
    /**
     * Vehicles assigned to this station with stats
     */
    200: {
        vehicles: Array<{
            id: number;
            internalNumber: string | null;
            plate: string | null;
            descriptionType: string | null;
            class: string | null;
            descriptionOperationalStatus: string | null;
            stats: {
                incidentCount: number;
                avgResponseTimeSeconds: number | null;
            };
        }>;
    };
};

export type GetStationsByKeyVehiclesResponse = GetStationsByKeyVehiclesResponses[keyof GetStationsByKeyVehiclesResponses];

export type GetStationsByNameByNameData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/stations/by-name/{name}';
};

export type GetStationsByNameByNameErrors = {
    /**
     * Station not found
     */
    404: {
        message: string;
    };
};

export type GetStationsByNameByNameError = GetStationsByNameByNameErrors[keyof GetStationsByNameByNameErrors];

export type GetStationsByNameByNameResponses = {
    /**
     * Station details
     */
    200: {
        station: {
            id: number;
            name: string;
            stationKey: string;
            radioChannel: string | null;
            latitude: string;
            longitude: string;
            address: string | null;
            phoneNumber: string | null;
            fax: string | null;
            email: string | null;
            isOperative: boolean | null;
        };
    };
};

export type GetStationsByNameByNameResponse = GetStationsByNameByNameResponses[keyof GetStationsByNameByNameResponses];

export type GetStationsByKeyImageOriginalData = {
    body?: never;
    path: {
        key: string;
    };
    query: {
        token: string;
    };
    url: '/stations/{key}/image/original';
};

export type GetStationsByKeyImageOriginalErrors = {
    /**
     * Invalid or missing token
     */
    401: {
        message: string;
    };
    /**
     * Station image not found
     */
    404: {
        message: string;
    };
};

export type GetStationsByKeyImageOriginalError = GetStationsByKeyImageOriginalErrors[keyof GetStationsByKeyImageOriginalErrors];

export type GetStationsByKeyImageOriginalResponses = {
    /**
     * Original station image
     */
    200: Blob | File;
};

export type GetStationsByKeyImageOriginalResponse = GetStationsByKeyImageOriginalResponses[keyof GetStationsByKeyImageOriginalResponses];

export type GetStationsByKeyImageData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/stations/{key}/image';
};

export type GetStationsByKeyImageErrors = {
    /**
     * Station image not found
     */
    404: {
        message: string;
    };
    /**
     * Failed to fetch station image
     */
    502: {
        message: string;
    };
};

export type GetStationsByKeyImageError = GetStationsByKeyImageErrors[keyof GetStationsByKeyImageErrors];

export type GetStationsByKeyImageResponses = {
    /**
     * Station image
     */
    200: Blob | File;
};

export type GetStationsByKeyImageResponse = GetStationsByKeyImageResponses[keyof GetStationsByKeyImageResponses];

export type GetAdminIncidentsData = {
    body?: never;
    path?: never;
    query: {
        from: string;
        to: string;
    };
    url: '/admin/incidents';
};

export type GetAdminIncidentsErrors = {
    /**
     * Missing or invalid admin-token cookie
     */
    401: {
        message: string;
    };
    /**
     * Failed to fetch incident list from SIGAE
     */
    500: {
        message: string;
    };
    /**
     * Admin synchronization is disabled
     */
    503: {
        message: string;
    };
};

export type GetAdminIncidentsError = GetAdminIncidentsErrors[keyof GetAdminIncidentsErrors];

export type GetAdminIncidentsResponses = {
    /**
     * List of incidents from SIGAE within the date range
     */
    200: {
        incidents: Array<{
            id: number;
            consecutivo: string;
            fecha: string;
            hora: string;
            direccion: string;
            tipoIncidente: string;
            estacionResponsable: string;
            synced: boolean;
        }>;
    };
};

export type GetAdminIncidentsResponse = GetAdminIncidentsResponses[keyof GetAdminIncidentsResponses];

export type PostAdminIncidentsData = {
    body?: {
        incidentIds: Array<number>;
    };
    path?: never;
    query?: never;
    url: '/admin/incidents';
};

export type PostAdminIncidentsErrors = {
    /**
     * Missing or invalid admin-token cookie
     */
    401: {
        message: string;
    };
    /**
     * Admin synchronization is disabled
     */
    503: {
        message: string;
    };
};

export type PostAdminIncidentsError = PostAdminIncidentsErrors[keyof PostAdminIncidentsErrors];

export type PostAdminIncidentsResponses = {
    /**
     * Sync results for the provided incident IDs
     */
    200: {
        success: boolean;
        totalIncidents: number;
        syncedIncidents: number;
        failedIncidents: number;
        failedResults: Array<{
            incidentId: number;
            success: boolean;
            error?: string;
        }>;
    };
};

export type PostAdminIncidentsResponse = PostAdminIncidentsResponses[keyof PostAdminIncidentsResponses];

export type PostAdminIncidentsByIdData = {
    body?: never;
    path: {
        id: number | null;
    };
    query?: never;
    url: '/admin/incidents/{id}';
};

export type PostAdminIncidentsByIdErrors = {
    /**
     * Missing or invalid admin-token cookie
     */
    401: {
        message: string;
    };
    /**
     * Admin synchronization is disabled
     */
    503: {
        message: string;
    };
};

export type PostAdminIncidentsByIdError = PostAdminIncidentsByIdErrors[keyof PostAdminIncidentsByIdErrors];

export type PostAdminIncidentsByIdResponses = {
    /**
     * Sync result for the incident
     */
    200: {
        incidentId: number;
        success: boolean;
        error?: string;
    };
};

export type PostAdminIncidentsByIdResponse = PostAdminIncidentsByIdResponses[keyof PostAdminIncidentsByIdResponses];

export type GetStatsYearRecapData = {
    body?: never;
    path?: never;
    query?: {
        year?: number;
    };
    url: '/stats/year-recap';
};

export type GetStatsYearRecapResponses = {
    /**
     * Year-to-date statistics about emergency response
     */
    200: {
        year: number;
        totalIncidents: number;
        frequency: number | null;
        busiestDate: {
            date: string;
            count: number;
        } | null;
        busiestStation: {
            name: string;
            count: number;
        } | null;
        busiestVehicle: {
            internalNumber: string;
            count: number;
        } | null;
        mostPopularIncidentType: {
            name: string;
            count: number;
        } | null;
    };
};

export type GetStatsYearRecapResponse = GetStatsYearRecapResponses[keyof GetStatsYearRecapResponses];

export type GetStatsTopDispatchedStationsData = {
    body?: never;
    path?: never;
    query?: {
        timeRange?: number;
    };
    url: '/stats/top-dispatched-stations';
};

export type GetStatsTopDispatchedStationsResponses = {
    /**
     * Top dispatched stations by count
     */
    200: Array<{
        name: string;
        key: string | null;
        total: number;
        responsible: number;
        support: number;
    }>;
};

export type GetStatsTopDispatchedStationsResponse = GetStatsTopDispatchedStationsResponses[keyof GetStatsTopDispatchedStationsResponses];

export type GetStatsTopResponseTimesData = {
    body?: never;
    path?: never;
    query?: {
        timeRange?: number;
    };
    url: '/stats/top-response-times';
};

export type GetStatsTopResponseTimesResponses = {
    /**
     * Station response time rankings (fastest, slowest, and national average)
     */
    200: Array<{
        name: string;
        key: string | null;
        avgResponseTimeMinutes: number;
        totalDispatches: number;
        fastestResponseMinutes: number;
        slowestResponseMinutes: number;
        category: 'fastest' | 'slowest' | 'average';
    }>;
};

export type GetStatsTopResponseTimesResponse = GetStatsTopResponseTimesResponses[keyof GetStatsTopResponseTimesResponses];

export type GetStatsIncidentsByDayOfWeekData = {
    body?: never;
    path?: never;
    query?: {
        timeRange?: number;
    };
    url: '/stats/incidents-by-day-of-week';
};

export type GetStatsIncidentsByDayOfWeekResponses = {
    /**
     * Incidents distribution by day of week
     */
    200: Array<{
        dayOfWeek: string;
        count: number;
    }>;
};

export type GetStatsIncidentsByDayOfWeekResponse = GetStatsIncidentsByDayOfWeekResponses[keyof GetStatsIncidentsByDayOfWeekResponses];

export type GetStatsIncidentsByHourData = {
    body?: never;
    path?: never;
    query?: {
        timeRange?: number;
    };
    url: '/stats/incidents-by-hour';
};

export type GetStatsIncidentsByHourResponses = {
    /**
     * Incidents distribution by hour of day
     */
    200: Array<{
        hour: number;
        count: number;
        displayHour: string;
    }>;
};

export type GetStatsIncidentsByHourResponse = GetStatsIncidentsByHourResponses[keyof GetStatsIncidentsByHourResponses];

export type GetStatsDailyIncidentsData = {
    body?: never;
    path?: never;
    query?: {
        timeRange?: number;
    };
    url: '/stats/daily-incidents';
};

export type GetStatsDailyIncidentsResponses = {
    /**
     * Daily incidents comparison between current and previous period
     */
    200: {
        data: Array<{
            date: string;
            dayOffset: number;
            current: number;
            previous: number;
            displayDate: string;
        }>;
        summary: {
            currentTotal: number;
            previousTotal: number;
            percentageChange: number;
        };
    };
};

export type GetStatsDailyIncidentsResponse = GetStatsDailyIncidentsResponses[keyof GetStatsDailyIncidentsResponses];

export type GetStatsSystemOverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stats/system-overview';
};

export type GetStatsSystemOverviewResponses = {
    /**
     * System overview statistics
     */
    200: {
        stationCount: number;
        activeVehicleCount: number;
        avgResponseTimeMinutes: number | null;
    };
};

export type GetStatsSystemOverviewResponse = GetStatsSystemOverviewResponses[keyof GetStatsSystemOverviewResponses];
