// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/bomberos/hono` | (string & {});
};

export type GetIncidentsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        cursor?: number | null;
        station?: string | null;
        view?: 'default' | 'map';
        sortBy?: 'id' | 'incidentTimestamp';
        sortOrder?: 'asc' | 'desc';
        startTime?: string | null;
        endTime?: string | null;
    };
    url: '/incidents';
};

export type GetIncidentsErrors = {
    /**
     * Invalid time range (must be positive and not exceed 3 days for map view)
     */
    400: {
        message: string;
    };
};

export type GetIncidentsError = GetIncidentsErrors[keyof GetIncidentsErrors];

export type GetIncidentsResponses = {
    /**
     * List of incidents. 'default' view returns paginated results with nextCursor; 'map' view returns all matching coordinates (max 3 day range).
     */
    200: {
        view: 'default';
        incidents: Array<{
            id: number;
            slug: string;
            isOpen: boolean;
            EEConsecutive: string | null;
            address: string | null;
            incidentTimestamp: string;
            importantDetails: string | null;
            specificIncidentCode: string | null;
            incidentType: string | null;
            responsibleStation: string | null;
            specificIncidentType: string | null;
            dispatchedVehiclesCount: number;
            dispatchedStationsCount: number;
        }>;
        nextCursor: number | null;
    } | {
        view: 'map';
        incidents: Array<{
            id: number;
            slug: string;
            latitude: string;
            longitude: string;
        }>;
    };
};

export type GetIncidentsResponse = GetIncidentsResponses[keyof GetIncidentsResponses];

export type GetIncidentsHighlightedData = {
    body?: never;
    path?: never;
    query?: {
        timeRange?: number;
    };
    url: '/incidents/highlighted';
};

export type GetIncidentsHighlightedResponses = {
    /**
     * List of highlighted incidents sorted by total emergency response deployment
     */
    200: {
        incidents: Array<{
            id: number;
            slug: string;
            incidentTimestamp: string;
            details: string;
            address: string;
            responsibleStation: string;
            dispatchedVehiclesCount: number;
            dispatchedStationsCount: number;
            hasMapImage: boolean;
        }>;
    };
};

export type GetIncidentsHighlightedResponse = GetIncidentsHighlightedResponses[keyof GetIncidentsHighlightedResponses];

export type GetIncidentsByIdData = {
    body?: never;
    path: {
        id: number | null;
    };
    query?: never;
    url: '/incidents/{id}';
};

export type GetIncidentsByIdErrors = {
    /**
     * Incident not found
     */
    404: {
        message: string;
    };
};

export type GetIncidentsByIdError = GetIncidentsByIdErrors[keyof GetIncidentsByIdErrors];

export type GetIncidentsByIdResponses = {
    /**
     * Detailed incident information
     */
    200: {
        incident: {
            id: number;
            title: string;
            incidentTimestamp: string;
            dispatchType: string;
            actualType: string | null;
            address: string | null;
            isOpen: boolean;
            modifiedAt: string | null;
            cantonName: string | null;
            provinceName: string | null;
            districtName: string | null;
            location: string | null;
            latitude: string | null;
            longitude: string | null;
            hasMapImage: boolean;
            EEConsecutive: string | null;
            dispatchedVehiclesCount: number;
            dispatchedStationsCount: number;
            dispatchedStations: Array<{
                name: string;
                stationKey: string;
                isResponsible: boolean;
                vehicles: Array<{
                    internalNumber: string;
                    dispatchTime: string | null;
                    arrivalTime: string | null;
                    departureTime: string | null;
                }>;
            }>;
        };
        statistics: {
            currentYear: number;
            currentYearCount: number;
            currentYearCantonCount: number;
            previousYear: number;
            previousYearCount: number;
        };
    };
};

export type GetIncidentsByIdResponse = GetIncidentsByIdResponses[keyof GetIncidentsByIdResponses];

export type GetIncidentsByIdTimelineData = {
    body?: never;
    path: {
        id: number | null;
    };
    query?: never;
    url: '/incidents/{id}/timeline';
};

export type GetIncidentsByIdTimelineErrors = {
    /**
     * Incident not found
     */
    404: {
        message: string;
    };
};

export type GetIncidentsByIdTimelineError = GetIncidentsByIdTimelineErrors[keyof GetIncidentsByIdTimelineErrors];

export type GetIncidentsByIdTimelineResponses = {
    /**
     * Timeline events for the incident
     */
    200: {
        incidentId: number;
        events: Array<{
            id: string;
            date: string;
            title: string;
            description?: string;
        }>;
    };
};

export type GetIncidentsByIdTimelineResponse = GetIncidentsByIdTimelineResponses[keyof GetIncidentsByIdTimelineResponses];

export type GetIncidentsByIdResponseTimesData = {
    body?: never;
    path: {
        id: number | null;
    };
    query?: never;
    url: '/incidents/{id}/response-times';
};

export type GetIncidentsByIdResponseTimesErrors = {
    /**
     * Incident not found
     */
    404: {
        message: string;
    };
};

export type GetIncidentsByIdResponseTimesError = GetIncidentsByIdResponseTimesErrors[keyof GetIncidentsByIdResponseTimesErrors];

export type GetIncidentsByIdResponseTimesResponses = {
    /**
     * Response time breakdown for dispatched vehicles
     */
    200: {
        incidentId: number;
        isOpen: boolean;
        vehicles: Array<{
            id: number;
            vehicle: string;
            station: string;
            dispatchedTime: string | null;
            arrivalTime: string | null;
            departureTime: string | null;
            baseReturnTime: string | null;
            responseTimeSeconds: number;
            onSceneTimeSeconds: number;
            returnTimeSeconds: number;
            totalTimeSeconds: number;
            isEnRoute: boolean;
        }>;
    };
};

export type GetIncidentsByIdResponseTimesResponse = GetIncidentsByIdResponseTimesResponses[keyof GetIncidentsByIdResponseTimesResponses];

export type GetIncidentsByIdOgData = {
    body?: never;
    path: {
        id: number | null;
    };
    query?: never;
    url: '/incidents/{id}/og';
};

export type GetIncidentsByIdOgErrors = {
    /**
     * Incident not found
     */
    404: {
        message: string;
    };
};

export type GetIncidentsByIdOgError = GetIncidentsByIdOgErrors[keyof GetIncidentsByIdOgErrors];

export type GetIncidentsByIdOgResponses = {
    /**
     * OG Image for the incident
     */
    200: Blob | File;
};

export type GetIncidentsByIdOgResponse = GetIncidentsByIdOgResponses[keyof GetIncidentsByIdOgResponses];

export type GetIncidentsByIdMapOriginalData = {
    body?: never;
    path: {
        id: number | null;
    };
    query: {
        token: string;
    };
    url: '/incidents/{id}/map/original';
};

export type GetIncidentsByIdMapOriginalErrors = {
    /**
     * Invalid coordinates
     */
    400: {
        message: string;
    };
    /**
     * Invalid or missing token
     */
    401: {
        message: string;
    };
    /**
     * Incident not found
     */
    404: {
        message: string;
    };
    /**
     * Failed to fetch map image
     */
    502: {
        message: string;
    };
};

export type GetIncidentsByIdMapOriginalError = GetIncidentsByIdMapOriginalErrors[keyof GetIncidentsByIdMapOriginalErrors];

export type GetIncidentsByIdMapOriginalResponses = {
    /**
     * Original map image from Mapbox (PNG)
     */
    200: Blob | File;
};

export type GetIncidentsByIdMapOriginalResponse = GetIncidentsByIdMapOriginalResponses[keyof GetIncidentsByIdMapOriginalResponses];

export type GetIncidentsByIdMapData = {
    body?: never;
    path: {
        id: number | null;
    };
    query?: never;
    url: '/incidents/{id}/map';
};

export type GetIncidentsByIdMapErrors = {
    /**
     * Invalid coordinates
     */
    400: {
        message: string;
    };
    /**
     * Incident not found
     */
    404: {
        message: string;
    };
    /**
     * Failed to fetch map image
     */
    502: {
        message: string;
    };
};

export type GetIncidentsByIdMapError = GetIncidentsByIdMapErrors[keyof GetIncidentsByIdMapErrors];

export type GetIncidentsByIdMapResponses = {
    /**
     * Map image for the incident
     */
    200: Blob | File;
};

export type GetIncidentsByIdMapResponse = GetIncidentsByIdMapResponses[keyof GetIncidentsByIdMapResponses];

export type GetStationsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        cursor?: number | null;
        search?: string;
        isOperative?: boolean | null;
        view?: 'default' | 'map';
    };
    url: '/stations';
};

export type GetStationsResponses = {
    /**
     * Paginated list of stations
     */
    200: {
        view: 'default';
        stations: Array<{
            id: number;
            name: string;
            stationKey: string;
            address: string | null;
            latitude: string;
            longitude: string;
            isOperative: boolean | null;
        }>;
        nextCursor: number | null;
    } | {
        view: 'map';
        stations: Array<{
            id: number;
            stationKey: string;
            latitude: string;
            longitude: string;
        }>;
    };
};

export type GetStationsResponse = GetStationsResponses[keyof GetStationsResponses];

export type GetStationsByKeyData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/stations/{key}';
};

export type GetStationsByKeyErrors = {
    /**
     * Station not found
     */
    404: {
        message: string;
    };
};

export type GetStationsByKeyError = GetStationsByKeyErrors[keyof GetStationsByKeyErrors];

export type GetStationsByKeyResponses = {
    /**
     * Station details
     */
    200: {
        station: {
            id: number;
            name: string;
            stationKey: string;
            radioChannel: string | null;
            latitude: string;
            longitude: string;
            address: string | null;
            phoneNumber: string | null;
            fax: string | null;
            email: string | null;
            isOperative: boolean | null;
        };
    };
};

export type GetStationsByKeyResponse = GetStationsByKeyResponses[keyof GetStationsByKeyResponses];

export type GetStationsByKeyImageOriginalData = {
    body?: never;
    path: {
        key: string;
    };
    query: {
        token: string;
    };
    url: '/stations/{key}/image/original';
};

export type GetStationsByKeyImageOriginalErrors = {
    /**
     * Invalid or missing token
     */
    401: {
        message: string;
    };
    /**
     * Station image not found
     */
    404: {
        message: string;
    };
};

export type GetStationsByKeyImageOriginalError = GetStationsByKeyImageOriginalErrors[keyof GetStationsByKeyImageOriginalErrors];

export type GetStationsByKeyImageOriginalResponses = {
    /**
     * Original station image
     */
    200: Blob | File;
};

export type GetStationsByKeyImageOriginalResponse = GetStationsByKeyImageOriginalResponses[keyof GetStationsByKeyImageOriginalResponses];

export type GetStationsByKeyImageData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/stations/{key}/image';
};

export type GetStationsByKeyImageErrors = {
    /**
     * Station image not found
     */
    404: {
        message: string;
    };
    /**
     * Failed to fetch station image
     */
    502: {
        message: string;
    };
};

export type GetStationsByKeyImageError = GetStationsByKeyImageErrors[keyof GetStationsByKeyImageErrors];

export type GetStationsByKeyImageResponses = {
    /**
     * Station image
     */
    200: Blob | File;
};

export type GetStationsByKeyImageResponse = GetStationsByKeyImageResponses[keyof GetStationsByKeyImageResponses];

export type GetAdminIncidentsData = {
    body?: never;
    path?: never;
    query: {
        from: string;
        to: string;
    };
    url: '/admin/incidents';
};

export type GetAdminIncidentsErrors = {
    /**
     * Missing or invalid admin-token cookie
     */
    401: {
        message: string;
    };
    /**
     * Failed to fetch incident list from SIGAE
     */
    500: {
        message: string;
    };
    /**
     * Admin synchronization is disabled
     */
    503: {
        message: string;
    };
};

export type GetAdminIncidentsError = GetAdminIncidentsErrors[keyof GetAdminIncidentsErrors];

export type GetAdminIncidentsResponses = {
    /**
     * List of incidents from SIGAE within the date range
     */
    200: {
        incidents: Array<{
            id: number;
            consecutivo: string;
            fecha: string;
            hora: string;
            direccion: string;
            tipoIncidente: string;
            estacionResponsable: string;
            synced: boolean;
        }>;
    };
};

export type GetAdminIncidentsResponse = GetAdminIncidentsResponses[keyof GetAdminIncidentsResponses];

export type PostAdminIncidentsData = {
    body?: {
        incidentIds: Array<number>;
    };
    path?: never;
    query?: never;
    url: '/admin/incidents';
};

export type PostAdminIncidentsErrors = {
    /**
     * Missing or invalid admin-token cookie
     */
    401: {
        message: string;
    };
    /**
     * Admin synchronization is disabled
     */
    503: {
        message: string;
    };
};

export type PostAdminIncidentsError = PostAdminIncidentsErrors[keyof PostAdminIncidentsErrors];

export type PostAdminIncidentsResponses = {
    /**
     * Sync results for the provided incident IDs
     */
    200: {
        success: boolean;
        totalIncidents: number;
        syncedIncidents: number;
        failedIncidents: number;
        failedResults: Array<{
            incidentId: number;
            success: boolean;
            error?: string;
        }>;
    };
};

export type PostAdminIncidentsResponse = PostAdminIncidentsResponses[keyof PostAdminIncidentsResponses];

export type PostAdminIncidentsByIdData = {
    body?: never;
    path: {
        id: number | null;
    };
    query?: never;
    url: '/admin/incidents/{id}';
};

export type PostAdminIncidentsByIdErrors = {
    /**
     * Missing or invalid admin-token cookie
     */
    401: {
        message: string;
    };
    /**
     * Admin synchronization is disabled
     */
    503: {
        message: string;
    };
};

export type PostAdminIncidentsByIdError = PostAdminIncidentsByIdErrors[keyof PostAdminIncidentsByIdErrors];

export type PostAdminIncidentsByIdResponses = {
    /**
     * Sync result for the incident
     */
    200: {
        incidentId: number;
        success: boolean;
        error?: string;
    };
};

export type PostAdminIncidentsByIdResponse = PostAdminIncidentsByIdResponses[keyof PostAdminIncidentsByIdResponses];

export type GetStatsYearRecapData = {
    body?: never;
    path?: never;
    query?: {
        year?: number;
    };
    url: '/stats/year-recap';
};

export type GetStatsYearRecapResponses = {
    /**
     * Year-to-date statistics about emergency response
     */
    200: {
        year: number;
        totalIncidents: number;
        frequency: number | null;
        busiestDate: {
            date: string;
            count: number;
        } | null;
        busiestStation: {
            name: string;
            count: number;
        } | null;
        busiestVehicle: {
            internalNumber: string;
            count: number;
        } | null;
        mostPopularIncidentType: {
            name: string;
            count: number;
        } | null;
    };
};

export type GetStatsYearRecapResponse = GetStatsYearRecapResponses[keyof GetStatsYearRecapResponses];
