name: Build app
on:
  push:
    branches: ["main"]

jobs:
  amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD  }}

      - name: Build image and push to registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/sync/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.REGISTRY }}/${{ secrets.SYNC_IMAGE_NAME }}:latest

      - name: Trigger deploy
        run: |
          curl --request GET '${{ secrets.SYNC_DEPLOY_WEBHOOK_URL }}'